import React,{useState} from 'react';
import Navbar from '../components/Navbar';
import api from '../api/api';
const types=['All','Hostel','PG','Budget Hotel','Dharamshala','Camping'];
export default function Stays(){
  const[items,setItems]=useState([]);const[searched,setSearched]=useState(false);const[filters,setFilters]=useState({type:'All',location:'',maxPrice:''});
  async function search(e){e.preventDefault();setSearched(true);const{data}=await api.get('/features/stays',{params:filters});setItems(data)}
  return <><Navbar/><main className="max-w-6xl mx-auto px-4 py-10"><h1 className="text-3xl font-bold">Budget Stay Finder</h1><p className="text-slate-600 mt-2">Enter location and budget to search student-friendly stays.</p><form onSubmit={search} className="card mt-6 grid md:grid-cols-3 gap-3"><select className="input" value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}>{types.map(t=><option key={t}>{t}</option>)}</select><input className="input" placeholder="Location" value={filters.location} onChange={e=>setFilters({...filters,location:e.target.value})}/><input className="input" type="number" placeholder="Max price/night" value={filters.maxPrice} onChange={e=>setFilters({...filters,maxPrice:e.target.value})}/><button className="btn md:col-span-3">Search Stays</button></form>{!searched&&<p className="text-slate-500 mt-6">Search using your preferred location and price.</p>}<section className="grid md:grid-cols-3 gap-5 mt-6">{items.map(s=><div className="card" key={s.name}><h2 className="text-xl font-bold">{s.name}</h2><p className="text-slate-600">{s.location} • {s.type}</p><p className="mt-2">⭐ {s.rating} {s.verified?'• Verified ✅':'• Unverified'}</p><p className="text-2xl font-bold text-orange-600 mt-3">₹{s.price}/night</p></div>)}</section></main></>;
}
